@url = https://api.jsonbin.io/v3

###

# HTTP/1.1 422 Unprocessable Entity
GET {{url}}/b/xxx HTTP/1.1
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}

### 

# HTTP/1.1 400 Bad Request
# { "message": "Bin cannot be blank" }
POST {{url}}/b HTTP/1.1
Content-Type: application/json; charset=utf-8
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}
X-Bin-Private: true
X-Collection-Id: {{$dotenv JSONBIN_COLLECTION_ID}}

{}

###

# HTTP/1.1 400 Bad Request
#
# {
#   "message": "Schema Doc Validation Mismatch: items[0] Should have required property 'alias'",
#   "schemaDocID": "...",
#   "schemaDocName": "..."
# }
POST {{url}}/b HTTP/1.1
Content-Type: application/json; charset=utf-8
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}
X-Bin-Private: true
X-Collection-Id: {{$dotenv JSONBIN_COLLECTION_ID}}

{
  "items": [
    {
      "url": "https://nju33.com"
    }
  ]
}

###

# @name createBin

# HTTP/1.1 200 OK
#
# {
#   "record": {
#     "items": [
#       {
#         "alias": "nju33",
#         "url": "https://nju33.com"
#       }
#     ]
#   },
#   "metadata": {
#     "id": "...",
#     "createdAt": "...",
#     "private": true,
#     "collectionId": "..."
#   }
# }
POST {{url}}/b HTTP/1.1
Content-Type: application/json; charset=utf-8
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}
X-Bin-Private: true
X-Collection-Id: {{$dotenv JSONBIN_COLLECTION_ID}}

{
  "items": [
    {
      "alias": "nju33",
      "url": "https://nju33.com"
    }
  ]
}

###

# HTTP/1.1 200 OK
#
# {
#   "record": {
#     "items": [
#       {
#         "alias": "nju33",
#         "url": "https://nju33.com"
#       }
#     ]
#   },
#   "metadata": {
#     "id": "...",
#     "private": true,
#     "collectionId": "..."
#   }
# }
GET {{url}}/b/{{createBin.response.body.metadata.id}} HTTP/1.1
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}

###

# HTTP/1.1 200 OK
#
# {
#   "record": {
#     "items": [
#       {
#         "alias": "foo-nju33",
#         "url": "https://foo-nju33.com"
#       }
#     ]
#   },
#   "metadata": {
#     "parentId": "...",
#     "private": true
#   }
# }
PUT {{url}}/b/{{createBin.response.body.metadata.id}} HTTP/1.1
Content-Type: application/json; charset=utf-8
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}

{
  "items": [
    {
      "alias": "foo-nju33",
      "url": "https://foo-nju33.com"
    }
  ]
}


###

# HTTP/1.1 200 OK
#
# {
#   "metadata": {
#     "id": "5e9dffd4435f5604bb45011b",
#     "versionsDeleted": 0
#   },
#   "message": "Bin deleted successfully"
# }
DELETE {{url}}/b/{{createBin.response.body.metadata.id}} HTTP/1.1
X-Master-Key: {{$dotenv JSONBIN_TOKEN}}