service: chrome-ll

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-webpack
custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false
    packager: yarn

functions:
  hello:
    handler: handler.hello
